# Generated by Django 4.0.4 on 2022-04-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id'], 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
